#!/usr/bin/env php
<?php

if (!isset($argv[2]) || !is_numeric($argv[2])) {
    echo "usage: gzsplit gzipfile [line count]\n";
    echo "   ex) gzsplit hugefile.gz 1000000\n";
    exit;
}

$fh = gzopen($argv[1], 'r');
$threshold = $argv[2];
$seq = 0;
$fileseq = 0;
$gzw = null;
while (!gzeof($fh)) {
    if ($gzw == null) {
        $gzw = gzopen($argv[1] . '.' . $fileseq, 'w');
    }
    $line = gzgets($fh, 4096);
    gzwrite($gzw, $line);
    if (++$seq == $threshold) {
        gzclose($gzw);
        $gzw = null;
        $seq = 0;
        $fileseq++;
    }
}
gzclose($fh);
